version: '3'

services:
  db-users:
    image: postgres
    container_name: db-users
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-service
    ports:
      - "5433:5432"
    volumes:
      - my-db-users:/var/lib/postgresql/data
    networks:
      my_net:

  db-auth:
    image: postgres
    container_name: db-auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth-service
    ports:
      - "5435:5432"
    volumes:
      - my-db-auth:/var/lib/postgresql/data
    networks:
      my_net:

  db-device:
    image: postgres
    container_name: db-device
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: device-service
    ports:
      - "5434:5432"
    volumes:
      - my-db-device:/var/lib/postgresql/data
    networks:
      my_net:

  db-monitoring:
    image: postgres
    container_name: db-monitoring
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: monitoring-service
    ports:
      - "5436:5432"
    volumes:
      - my-db-monitoring:/var/lib/postgresql/data
    networks:
      my_net:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-frontend
    restart: unless-stopped
    networks:
      my_net:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      my_net:
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80" # The HTTP port
      # - "443:443" # The HTTPS port
      - "8080:8080" # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Traefik can listen to the Docker events
      - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Static configuration file
      - "./dynamic:/etc/traefik/dynamic:ro" # Dynamic configuration files
      - "./logs:/var/log/traefik" # Log files
    develop: # Enable live reload of dynamic configuration files on Windows, if using Unix based system needs to be commented out
      watch:
        - path: ./dynamic                   # watch the whole folder
          action: restart
    networks:
      my_net:


  spring-demo:
    build:
      context: ./userService
      dockerfile: ./Dockerfile
    container_name: spring-demo
    ports:
      - "8081:8080"
    environment:
      - DB_IP=db-users
      - DB_PORT=5432
      - DB_DBNAME=user-service
      - DB_USER=postgres
      - DB_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      my_net:
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-users:
        condition: service_started

  device-service:
    build:
      context: ./deviceService
      dockerfile: ./Dockerfile
    container_name: device-service
    ports:
      - "8082:8080"
    environment:
      - DB_IP=db-device
      - DB_PORT=5432
      - DB_DBNAME=device-service
      - DB_USER=postgres
      - DB_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      my_net:
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-device:
        condition: service_started

  auth-service:
    build:
      context: ./authService
      dockerfile: ./Dockerfile
    container_name: auth-service
    ports:
      - "8083:8080"
    environment:
      - DB_IP=db-auth
      - DB_PORT=5432
      - DB_DBNAME=auth-service
      - DB_USER=postgres
      - DB_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      my_net:
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-auth:
        condition: service_started

  monitoring-service:
    build:
      context: ./monitoringService
      dockerfile: ./Dockerfile
    container_name: monitoring-service
    ports:
      - "8084:8080"
    environment:
      - DB_IP=db-monitoring
      - DB_PORT=5432
      - DB_DBNAME=monitoring-service
      - DB_USER=postgres
      - DB_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      my_net:
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-monitoring:
        condition: service_started

  communication-service:
    build:
      context: ./comunicationService # Asigură-te că numele folderului e corect pe disk
      dockerfile: Dockerfile
    container_name: communication-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SERVER_PORT=8080 # Portul intern
    ports:
      - "8085:8080" # Expunem direct 8085 (opțional, pentru teste locale fără proxy)
    networks:
      - my_net


volumes:
  my-db-users:
  my-db-device:
  my-db-auth:
  my-db-monitoring:

networks:
  my_net:
    external: true
